### ISSUE TITLE
Provide the FluentWebElement as interface like WebElement

### ISSUE THREAD

**Issue by pussinboots** [SeleniumHQ/fluent-selenium#11]
Hi,

i working on a PageFactory approach for the FluentWebElement. For that i need a interface similar to the selenium WebElement, because i using the already provided PageFactory code from Selenium that is based on the JDK InvocationHandler that only can be used together with interfaces.

Wen i'am finished with the implementation i can share the code here too. 

have a nice day and keep working

**Comment by paul-hammant** [comment]
I don't understand - it is just not clear to me what you're asking for.  

You need additional methods?  Can you specify what you need changed please?

**Comment by pussinboots** [comment]
Hi, may i can try to discribe it better. At the moment there exists the class FluentWebElement right? This class offer all the nice fluent methods. My idea is it that FluentWebElement instance can be used in Page Object classes with this nice @FindBy annotations. This annotation could only inject java interfaces non classes. Selenium provide this WebElement interfaces which can be used with @FindBy annotations. To use FluentWebElement together with this annotations it has to be an interface. That would be one way the other way is to define a new interface like FluentWebElementIntf which define all the fluent methods and is implemented by the FluentWebElement. Its more clear now ? Have also a look to the Page Object and @FindBy selenium approach. Nice day frank

**Comment by paul-hammant** [comment]
Hi frank - still not getting it. How about some example code?  Remember to use the 'insert code' tool please - it looks like < > in the editor window.

**Comment by paul-hammant** [comment]
Any thoughts, Frank/ @pussinboots ?

**Comment by pussinboots** [comment]
Here are a example code what i want to achieve.

`class Webpage {
        @FindBy(id = "foobar") 
        private FluentWebElement foobar;

        public void doSomeThing() {
                     foobar.button().click();
        }`
}

**Comment by manoj9788** [comment]
@paul-hammant https://github.com/SeleniumHQ/selenium/tree/master/java/client/src/org/openqa/selenium/support/pagefactory

**Comment by steckerhalter** [comment]
Hi, I've also been wondering if something could be done so FluentWebElements could be used with the Selenium PageFactory. As I understand it the proxy requires an Interface but FluentWebElement is a class.

Probably another solution would be if I could convert the WebElement that was created by the PageFactory into a FluentWebElement. Is this possible? I tried some things but couldn't find a way to do it yet.

**Comment by paul-hammant** [comment]
Hi @steckerhalter. Would this do?

```
class Webpage {
        @FindBy(id = "foobar") 
        private WebElement foobar;
        public void doSomeThing() {
                 fluentize(foobar).button().click();
        }
}
```

Where fluentize() is a new static method?

**Comment by steckerhalter** [comment]
yeah I guess that should work... thx

**Comment by paul-hammant** [comment]
I think this is it - https://github.com/SeleniumHQ/fluent-selenium/blob/master/java/src/test/java/org/seleniumhq/selenium/fluent/FluentizeTest.java

**Comment by steckerhalter** [comment]
:+1:

**Comment by paul-hammant** [comment]
1.23 released with that
