### ISSUE TITLE
within(secs) does not work with angular2 (works fine)

### ISSUE THREAD

**Issue by faisalloe** [SeleniumHQ/fluent-selenium#13]
angular2 support ? (tested works fine)

**Comment by paul-hammant** [comment]
Can you give me an example app online ? If I can reproduce, I can fix it.

**Comment by faisalloe** [comment]
i will try setup jsFiddle for that. but trying to understand did some test this lib with angular 2 ?

**Comment by faisalloe** [comment]
sorry it works perfect. just tested again

**Comment by paul-hammant** [comment]
no probs!
