### ISSUE TITLE
Provide attributes for locating an element by containing text

### ISSUE THREAD

**Issue by rajaselvan** [SeleniumHQ/fluent-selenium#16]
Can you provide some fluent attributes or locators that take a text value and returns the element that encloses it.

I have to find a row in a table that contains a unique user name and click the link in the next cell. This can only be achieved by using text value and I found fluent selenium was missing this feature.

**Comment by ph-ms** [comment]
Show the code fragment you're expecting ...

```
fwd.table()..... ?
```

**Comment by rajaselvan** [comment]
For Example

1. fwd.span(By.partialText("Beyonce")) 
2. fwd.table(id("artistTable")).tr(contains("JayZ")).tds()
3. fwd.table(id("artistTable")).tr().contains("Adele").tds()

**Comment by paul-hammant** [comment]
1. By.partialText("Beyonce") would be something you write yourself I think. Have a read of https://mguillem.wordpress.com/2011/10/06/webdriver-subclass-the-by-class-to-define-own-locators/

^ It in itself would be usable by vanilla WebDriver too.

2. i think you'd want ..

    `fwd.table(id("artistTable")).tr(By.partialText("JayZ")).tds()`

.. and the same solution you do for [1] is used.

3. What is your intention with `.tr().contains("Adele").tds()` ? 
I mean contains() after tr() and before tds()

**Comment by paul-hammant** [comment]
OP ?
