### ISSUE TITLE
Can FluentSelenium change tabs for when tabs/windows are opened via _blank hrefs in anchor elements

### ISSUE THREAD

**Issue by vicbell** [SeleniumHQ/fluent-selenium#19]
Have a link `<a target="_blank" href="http://somenewpage"/>` in the current test page,after click the link then how could i switch to `http://somenewpage` and test the element of page `http://somenewpage` ?

tips:
`target="_blank"` add a new page, then there are two pages...

**Comment by paul-hammant** [comment]
You need to do that change in regular WebDriver. Fluent-Selenium can't help you there.

Read https://stackoverflow.com/questions/12729265/switch-tabs-using-selenium-webdriver-with-java and similar postings on StackOverflow

**Comment by vicbell** [comment]
Tks!

**Comment by paul-hammant** [comment]
You're welcome :)
