### ISSUE TITLE
about ElementNotInteractableException 

### ISSUE THREAD

**Issue by zgq1987** [SeleniumHQ/fluent-selenium#20]
many Thanks!!!
my code:
fwd.input(By.id("add_no_0")).within(Period.millis(10000)).sendKeys("55577");

Exception:
ElementNotInteractableException during invocation of: ?.input(By.id: addpsg_0).within(millis(10000)).sendKeys('55577')

Tips:
When run  ,  have this problem
When debug  ,   have no this problem

**Comment by paul-hammant** [comment]
I'll take a look

**Comment by paul-hammant** [comment]
Question: run vs debug in what IDE ?
I'm missing some context.

**Comment by paul-hammant** [comment]
OP's moved past this issue I guess.
