### ISSUE TITLE
NoClassDefFoundError

### ISSUE THREAD

**Issue by zgq1987** [SeleniumHQ/fluent-selenium#25]
when I do this:
driver.input(By.id("idNo")).sendKeys(“1111”);
error is :
 java.lang.NoClassDefFoundError: org/openqa/selenium/internal/Locatable

**Comment by paul-hammant** [comment]
Can you show me the whole project, including pom.xml ?

**Comment by paul-hammant** [comment]
OP non responsive. I guess they solved their problem themselves.
