### ISSUE TITLE
Find elements without having to use a tag

### ISSUE THREAD

**Issue by JonMR** [SeleniumHQ/fluent-selenium#5]
We have some h6 elements which AFAICT isn't supported by the API.  I see how I could fork the code and add support, but I don't really care that these elements are h6.

That got me thinking I'd like to be able to find elements without necessarily having to provide a tag name.  Maybe two methods elem(By by) and elems(By by).

I looked through the code and it looks like the tag name requirement is carried through the entire code base.  That prompted me to open this issue to see if you'd be open to such a change?

**Comment by paul-hammant** [comment]
.element(..) is in the API now.
